# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_allocation_ratio
#'
#' @description
#' Rcpp allocation ratio.
#'
#' @param biomass Numeric with biomass.
#' @param biomass_min,biomass_max Numeric with minum and maximum of biomass.
#' @param threshold,slope Numeric with function parameters.
#'
#' @details
#' Get ratio of bg and ag nutrient allocation. If ratio=1, all nutrients are
#' allocated in the bg biomass.
#'
#' If the threshold is positive, the ratio is r=1 for all biomass values below
#' the threshold. If threshold is negative, the ratio is be r=0.5 at the threshold.
#'
#' @references
#' User wmsmith on CrossValidated: "Is there a formula for an s-shaped curve with
#' domain and range [0,1]?" <https://stats.stackexchange.com/questions/214877/>
#'
#' @return double
#'
#' @aliases rcpp_allocation_ratio
#' @rdname rcpp_allocation_ratio
#' 
rcpp_allocation_ratio <- function(biomass, biomass_min, biomass_max, threshold, slope) {
    .Call(`_arrR_seagrass_rcpp_allocation_ratio`, biomass, biomass_min, biomass_max, threshold, slope)
}

#' rcpp_convert_nutr
#'
#' @description
#' Rcpp convert nutrients.
#'
#' @param x Numeric with nutrient amount.
#' @param to String to specify in which unit to convert.
#'
#' @details
#' Convert nutrients between g and umol based on molecular mass of (ammonium; NH4)
#'
#' @references
#' Molecular mass taken from <https://en.wikipedia.org/wiki/Ammonium>
#'
#' @return double
#'
#' @aliases rcpp_convert_nutr
#' @rdname rcpp_convert_nutr
#'
rcpp_convert_nutr <- function(x, to) {
    .Call(`_arrR_seagrass_rcpp_convert_nutr`, x, to)
}

#' rcpp_diffuse_values
#'
#' @description
#' Rcpp simulate diffusion.
#'
#' @param seafloor Matrix with seafloor values.
#' @param cell_adj Matrix with cell adjacencies.
#' @param nutrients_diffusion,detritus_diffusion,detritus_fish_diffusion Numeric with parameters.
#'
#' @details
#' Simulates the diffusion of the i) nutrients_pool, ii) detritus_pool,
#' and iii) detritus_fish_diffusion of each cell with its neighboring cells.
#' Scheduling is simulated pseudo-simultaneous.
#'
#' @return void
#'
#' @aliases rcpp_diffuse_values
#' @rdname rcpp_diffuse_values
#'
rcpp_diffuse_values <- function(seafloor, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_fish_diffusion) {
    invisible(.Call(`_arrR_seagrass_rcpp_diffuse_values`, seafloor, cell_adj, nutrients_diffusion, detritus_diffusion, detritus_fish_diffusion))
}

#' rcpp_get_adjacencies
#'
#' @description
#' Rcpp get adjacencies
#'
#' @param dimensions Vector with number or rows and cols
#' @param torus Logical if true, torus translation is used.
#'
#' @details
#' Get matrix with cell IDs of all neighboring cells. Indices start with 0
#' according to C++ indexing.
#'
#' @references
#' Code adapted from Robert J. Hijmans (2020). raster: Geographic Data Analysis
#' and Modeling. R package version 3.4-5. <https://CRAN.R-project.org/package=raster>
#'
#' @return matrix
#'
#' @aliases rcpp_get_adjacencies
#' @rdname rcpp_get_adjacencies
#'
#' @keywords internal
rcpp_get_adjacencies <- function(dimensions, torus) {
    .Call(`_arrR_seagrass_rcpp_get_adjacencies`, dimensions, torus)
}

#' rcpp_get_reef
#'
#' @description
#' Rcpp get reef matrix
#'
#' @param seafloor Matrix with seafloor values.
#'
#' @details
#' Get matrix with cell id and coordinates of reef cells.
#'
#' @return matrix
#'
#' @aliases rcpp_get_reef
#' @rdname rcpp_get_reef
#'
rcpp_get_reef <- function(seafloor) {
    .Call(`_arrR_seagrass_rcpp_get_reef`, seafloor)
}

#' rcpp_mineralization
#'
#' @description
#' Rcpp simulate mineralization.
#'
#' @param seafloor Matrix with seafloor values.
#' @param detritus_fish_decomp,detritus_mineralization seafloor Numeric with parameters.
#'
#' @details
#' Simulate mineralization of the detritus pool i.e., a ratio of the detritus pool
#' is added to the nutrients pool. The corresponding amount is removed from the
#' detritus pool.
#'
#' Also, simulates decomposition of the detritus fish_pool by removing a ratio and
#' adding it to the detritus pool.
#'
#' @references
#' DeAngelis, D.L., 1992. Dynamics of Nutrient Cycling and Food Webs. Springer
#' Netherlands, Dordrecht. <https://doi.org/10.1007/978-94-011-2342-6>
#'
#' @return void
#'
#' @aliases rcpp_mineralization
#' @rdname rcpp_mineralization
#'
rcpp_mineralization <- function(seafloor, detritus_mineralization, detritus_fish_decomp) {
    invisible(.Call(`_arrR_seagrass_rcpp_mineralization`, seafloor, detritus_mineralization, detritus_fish_decomp))
}

#' rcpp_nutr_input
#'
#' @description
#' Rcpp simulate nutrient input.
#'
#' @param seafloor Matrix with seafloor values.
#' @param nutrients_input Vector with amount of nutrient input each time step.
#'
#' @details
#' Simulate external nutrient input to the each cell. The \code{nutrients_input}
#' vector must have as many elements as \code{max_i} to add input each time step.
#'
#' If no nutrients should be added, set all values of \code{nutrients_input} to
#' zero.
#'
#' @references
#' DeAngelis, D.L., 1992. Dynamics of Nutrient Cycling and Food Webs. Springer
#' Netherlands, Dordrecht. <https://doi.org/10.1007/978-94-011-2342-6>
#'
#' @return void
#'
#' @aliases rcpp_nutr_input
#' @rdname rcpp_nutr_input
#'
rcpp_nutr_input <- function(seafloor, nutrients_input) {
    invisible(.Call(`_arrR_seagrass_rcpp_nutr_input`, seafloor, nutrients_input))
}

#' rcpp_nutr_output
#'
#' @description
#' Rcpp nutrient output.
#'
#' @param seafloor Matrix with seafloor values.
#' @param nutrients_loss,detritus_loss Double with fraction removed from each cell.
#'
#' @details
#' Simulates loss of nutrients (i.e., output of the system) for each cell and time
#' step. The loss is calculated as a ratio of the present nutrients in each cell.
#'
#' @references
#' DeAngelis, D.L., 1992. Dynamics of Nutrient Cycling and Food Webs. Springer
#' Netherlands, Dordrecht. <https://doi.org/10.1007/978-94-011-2342-6>
#'
#' @return void
#'
#' @aliases rcpp_nutr_output
#' @rdname rcpp_nutr_output
#'
rcpp_nutr_output <- function(seafloor, nutrients_loss, detritus_loss) {
    invisible(.Call(`_arrR_seagrass_rcpp_nutr_output`, seafloor, nutrients_loss, detritus_loss))
}

#' rcpp_nutr_uptake
#'
#' @description
#' Rcpp nutrient uptake.
#'
#' @param nutrients,biomass Numeric with nutrient and biomass amount of cell.
#' @param v_max,k_m,time_frac Numeric with parameters
#'
#' @details
#' Calculate nutrient uptake of each cells depending on avaiable nutrients in the
#' water column and bg and ag biomass. All values are scaled to the time period
#' which can be specified by \code{time_frac}. If the calculated uptake exceeds
#' the available amount, only the available amount is taken up.
#'
#' @references
#' DeAngelis, D.L., 1992. Dynamics of Nutrient Cycling and Food Webs. Springer
#' Netherlands, Dordrecht. <https://doi.org/10.1007/978-94-011-2342-6>
#'
#' Lee, K.-S., Dunton, K.H., 1999. Inorganic nitrogen acquisition in the seagrass
#' Thalassia testudinum: Development of a whole-plant nitrogen budget.
#' Limnol. Oceanogr. 44, 1204–1215. <https://doi.org/10.4319/lo.1999.44.5.1204>
#'
#' @return double
#'
#' @aliases rcpp_nutr_uptake
#' @rdname rcpp_nutr_uptake
#'
rcpp_nutr_uptake <- function(nutrients, biomass, v_max, k_m, time_frac) {
    .Call(`_arrR_seagrass_rcpp_nutr_uptake`, nutrients, biomass, v_max, k_m, time_frac)
}

#' rcpp_seagrass_growth
#'
#' @description
#' Rcpp seagrass growth.
#'
#' @param seafloor Matrix with seafloor values.
#' @param bg_v_max,bg_k_m,bg_gamma,ag_v_max,ag_k_m,ag_gamma Numeric with uptake parameters.
#' @param bg_biomass_max,bg_biomass_min,ag_biomass_max,ag_biomass_min Numerich with biomass values and parameters.
#' @param seagrass_slough,seagrass_thres,seagrass_slope,time_frac Numerich with various parameters.
#'
#' @details
#' Function to simulate processes of belowground and aboveground seagrass slough and
#' growth. All processes are simulated adapted after DeAngelis (1992).
#'
#' An amount of bg and ag slough is calculated pased on \code{seagrass_slough}.
#' The ratio is decreased the smaller the biomass gets and approximates zero for
#' the minimum capacity in a cell.
#'
#' The amount of nutrients that is taken up from the water column depend on the
#' seagrass belowground and aboveground biomass and available nutrients in each
#' cell.
#'
#' Allocation of uptake in bg or ag biomass depends on the uptake amount, the
#' amount of sloughed biomass and the corresponding capacities of bg and ag in the cells.
#' Additional growth (after slough was balanced) depends on the allocation ratio.
#'
#' Last, all cells in which either bg or ag biomass is above the maximum capacity,
#' all additionall biomass is sloughed.
#'
#' @references
#' DeAngelis, D.L., 1992. Dynamics of Nutrient Cycling and Food Webs. Springer
#' Netherlands, Dordrecht. <https://doi.org/10.1007/978-94-011-2342-6>
#'
#' @return void
#'
#' @aliases rcpp_seagrass_growth
#' @rdname rcpp_seagrass_growth
#'
rcpp_seagrass_growth <- function(seafloor, bg_v_max, bg_k_m, bg_gamma, ag_v_max, ag_k_m, ag_gamma, bg_biomass_max, bg_biomass_min, ag_biomass_max, ag_biomass_min, seagrass_thres, seagrass_slope, seagrass_slough, time_frac) {
    invisible(.Call(`_arrR_seagrass_rcpp_seagrass_growth`, seafloor, bg_v_max, bg_k_m, bg_gamma, ag_v_max, ag_k_m, ag_gamma, bg_biomass_max, bg_biomass_min, ag_biomass_max, ag_biomass_min, seagrass_thres, seagrass_slope, seagrass_slough, time_frac))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_arrR_seagrass_RcppExport_registerCCallable`)
})
